export const NEW_TYPES_CARTRIDGE = 'CARTRIDGE/NEW_TYPES_CARTRIDGE'
export const ADD_NEW_CARTRIDGE = 'CARTRIDGE/ADD_NEW_CARTRIDGE'
export const SHOW_MODAL_ADD_CARTRIDGE = 'CARTRIDGE/SHOW_MODAL_ADD_CARTRIDGE'
export const ADD_BRANCH = 'CARTRIDGE/ADD_BRANCH';
export const ADD_FINISH_REQUEST = 'CARTRIDGE/ADD_FINISH_REQUEST';
export const REMOVE_CARTRIDGE = 'CARTRIDGE/REMOVE_CARTRIDGE'

export const FILTER_BRANCH = 'FILTER/FILTER_BRANCH';
export const FILTER_MODEL = 'FILTER/FILTER_MODEL';

export const FINISH_REQUEST = 'FINISH/FINISH_REQUEST';

export const ADD_DEVICES = 'DEVICES/ADD_NEW_DEVICES';
export const DATA_EXPORT_IN_REPAIR = 'DATA_EXPORT_IN_REPAIR'
export const DATA_IMPORT_OF_REPAIR = 'DEVICES/DATA_IMPORT_OF_REPAIR'
export const DATA_EXPORT_TO_SU = 'DEVICES/DATA_EXPORT_TO_SU'

