export const NEW_TYPES_CARTRIDGE = 'CARTRIDGE/NEW_TYPES_CARTRIDGE'
export const ADD_NEW_CARTRIDGE = 'CARTRIDGE/ADD_NEW_CARTRIDGE'
export const REMOVE_CARTRIDGE = 'CARTRIDGE/REMOVE_CARTRIDGE'
export const ADD_DEVICES = 'DEVICES/ADD_NEW_DEVICES';